# Site settings
name: MZZZ
email: zqk_mz@136.com
author: MZZZ
#个人网站
url: https://github.com
#简历地址
resume_site: hhttps://mzqk.github.io/resume/
github: https://github.com/MZqk/
#项目名
baseurl: 
#描述
description: 

meta_description: MZ;Blog;
#座右铭
motto: 造出不一样得轮子
#标语
banner:  安于眼前，不止于现状 

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: MZqk
highlighter: rouge

# Build settings
markdown: kramdown 

baidu_analysis: 94be4b0f9fc5d94cc0d0415ea6761ae9

gems: [jekyll-paginate]

FB:
  comments :
    provider : 
    duoshuo:
        short_name : 
    disqus :
        short_name : 
    # facebook :
    #   appid : 123
    #   num_posts: 5
    #   width: 580
    #   colorscheme: light
